import { StdParagraph, BlogHeader } from "./utils";


const WhyCallInterventionist = () => 
  <div>
    <BlogHeader>Why Call an Interventionist?</BlogHeader>
    <StdParagraph>Substance abuse and addiction have debilitating effects on families as a whole.  The true addict or alcoholic’s life will never improve without abstinence.  Typically, as their life continues to spiral, their family members, partners, and friends are left to pick up the pieces.  Family members almost always exhaust their personal resources attempting to help their loved one.  They spend countless nights worrying about the safety and health of their loved one.  Seeking professional help is the first step for families that are battling addiction. </StdParagraph>
    <StdParagraph>Addiction is the only disease that requires a self-diagnosis in order to receive successful treatment.  If someone doesn’t realize they have a problem, they will not seek treatment.  Even when individuals realize they have a problem, that doesn’t always mean they’re ready to make a change.  The addict or alcoholic’s problem didn’t occur overnight, similarly, the process of getting sober takes a lot of time and effort to facilitate true healing.  Healing needs to occur for both the addicted individual and their loved ones. </StdParagraph>
    <StdParagraph>There are a variety of treatment services available for substance abuse and alcoholism, but if the person isn’t ready to change, those services are virtually useless.  The goal of an intervention process is to help the addict or alcoholic realize they need to seek help.  Once they come to the conclusion that they need help, these addiction treatment services become much more effective.</StdParagraph>
    <StdParagraph>There are a variety of different proven intervention modalities that are utilized in the field.  Each situation is different, depending on the situation, one modality might be more effective than the others.  The first step for the interventionist is to get a better understanding of the situation and what has been transpiring with the addict or alcoholic.  Once this information is collected, the interventionist will inform the family about his or her recommended intervention method.  Once the intervention method is determined, the process will move forward within that individual framework.</StdParagraph>
    <StdParagraph>The foundation of each intervention method is set upon several key principles.  Each method requires a lot of planning and communication.  The interventionist will help families set direct, but loving boundaries with the person of concern.  Finally, the intervention is just as important for the family’s healing as it is the addict or alcoholic’s recovery.  The goal is always to assist the addict or alcoholic in realizing that they need to get help.  These conversations can be extremely intense and difficult to manage for families.  The interventionist is there to help facilitate the process and ensure that it goes smoothly.  These are very emotional situations, and it is useful to have someone there who isn’t directly involved or affected by the person’s addiction.  At the end of the day, the interventionist is there to get the person of concern the proper level of care that they need, and to ensure the process is handled safely.</StdParagraph>
  </div>

export default WhyCallInterventionist;